### PR TITLE
Update microgrid client to v0.3

### PR DESCRIPTION
**Pull request by matthias-wende-frequenz**

### CODE REVIEW

**Comment by llucax** [comment]
Added a commit to fix the tests.

**Comment by llucax** [comment]
This probably needs an approval from someone else.

**Comment by llucax** [comment]
~Added~ Updated release notes.

**Review by llucax — APPROVED** [review]

**Comment by matthias-wende-frequenz** [comment]
> This probably needs an approval from someone else.

I guess so. Unfortunately I'm not allowed to approve :(.

**Review by daniel-zullo-frequenz — APPROVED** [review]

**Pull request merged**
