### PR TITLE
Clean ups and improvements to the resampler (mostly)

### LINKED ISSUE #59: Use the `datetime` produced by the timer in the resampling actor
The timer actually returns a `datetime` object at which the timer triggered.  We can actually pass it to the `resample` function and it can pass it down the chain.

_Originally posted by @sahas-subramanian-frequenz in https://github.com/frequenz-floss/frequenz-sdk-python/pull/32#discussion_r1010562794_

### LINKED ISSUE #60: Document the `ResamplingFunction`
### What's needed?

The `ResamplingFunction` type in the resampler is not properly documented.

### Proposed solution

We need to add good documentation for it.

### Use cases

_No response_

### Alternatives and workarounds

_No response_

### Additional context

Original thread:

* https://github.com/frequenz-floss/frequenz-sdk-python/pull/32#discussion_r1010322157

### PR DESCRIPTION
**Pull request by leandro-lucarella-frequenz**
This PR mainly moves classes from the resampler to the new `timeseries`
package, but it also includes some nox and test improvements and fixes.

It also uses the timestamp produced by the timer as the resampling timestamp,
unifying it across all the resampling levels for full consistency.

- Allow passing positional arguments to nox sessions
- Move resampling actor to frequenz.sdk.actor
- Move resampler classes to frequenz.sdk.timeseries.resampler
- Remove unnecessary usage of pytz
- Fix sample ordering in tests
- Use more intuitive variable names in resampler tests
- Use easier to debug fake times in tests
- Allow the resampler to use an external timestamp
- Use the timestamp provided by the timer receiver
- Document ResamplingFunction
- Move Sample to frequenz.sdk.timeseries

### CODE REVIEW

**Comment by leandro-lucarella-frequenz** [comment]
This might depend on https://github.com/frequenz-floss/frequenz-channels-python/pull/48, I am getting a lot of flakyness in tests, stalling at the grpc mocking layer. At some point the traceback showed issues with comparing time aware and native datetimes, but locally I still get sometimes stalled tests. It is very hard to find a way to reproduce and it doesn't always seem to be related to these changes, but it happens even when rebuilding the whole virtualenv.

**Comment by leandro-lucarella-frequenz** [comment]
This is also a step forward (needed preparation) for making the API more stable and for #56.

**Comment by leandro-lucarella-frequenz** [comment]
Updated:

* Added a few more cleanups (remove `pytz`)
* Minimized the flakiness of the resampling test, I had a double-failure, both the channels "native" datetime and the intrinsic flakiness of the tests were making my life debugging misserable
* Added a temporary commit to use frequenz-channels v0.x.x to config the fix works (and it does :tada:)

**Review by sahas-subramanian-frequenz — DISMISSED** [review]
This LGTM.  There's a commit updating channel version to the dev version.  Do you want to remove that and take this in,  and update channel version once there is a new release?

**Comment by leandro-lucarella-frequenz** [comment]
> This LGTM. There's a commit updating channel version to the dev version. Do you want to remove that and take this in, and update channel version once there is a new release?

I'll wait and see if we can make the channels release soon enough.

**Comment by leandro-lucarella-frequenz** [comment]
Updated to move the `data_pipeline` stuff to the data sourcing actor (and make some imports relative). I also renamed the commit to use the devel channels to remove the `TMP: `, I think we should merge this as is for now to unblock other PRs that might be better to rebase on top of this one. I created #71.

**Review by sahas-subramanian-frequenz — APPROVED** [review]

**Pull request merged**
