### PR TITLE
Add missing dependencies in documentation

### PR DESCRIPTION
**Pull request by mathias-baumann-frequenz**
Further dependencies I had to install to run pytest. Maybe this should go
somewhere else? not sure.

### CODE REVIEW

**Review by sahas-subramanian-frequenz — APPROVED** [review]
LGTM!

**Comment by shsms** [comment]
Oops,  looks like the DCO check failed.  Commits need to have a DCO statement (from `git -s`) and need to be gpg signed.

https://github.com/frequenz-floss/frequenz-sdk-python/pull/112/checks?check_run_id=10058811427
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by mathias-baumann-frequenz** [comment]
I would fix it, but I don't have force-push permissions for this branch :laughing:

**Comment by mathias-baumann-frequenz** [comment]
(I meant to create the PR from my own fork anyway, but made a mistake with the new github cli tool)

**Comment by shsms** [comment]
> I would fix it, but I don't have force-push permissions for this branch 

I don't either,  that's why I always make PRs from a fork :D

I cloned the upstream read-only with `https`, so can push only into my fork locally.

**Pull request closed without merging**
