### PR TITLE
Add documentation on how to receive power request results

### PR DESCRIPTION
**Pull request by Marenz**
Doh.

### CODE REVIEW

**Review by llucax — APPROVED** [review]
Super minor but the commit style is not to end the commit title with a full stop. Is fine to merge as is for me, just for future PRs.

**Comment by Marenz** [comment]
I fixed it for you <3

**Comment by Marenz** [comment]
.. or not? The push doesn't seem to go appear here

**Comment by llucax** [comment]
> .. or not? The push doesn't seem to go appear here

Next time :P

**Pull request merged**
