### PR TITLE
Remove deprecated modules

### PR DESCRIPTION
**Pull request by shsms**
There are no dependencies on the `_data_ingestion` and the `_data_handling` packages anymore and can be removed.

Removing them shaves of a little over a minute from a single `nox` run.

Based on #201

### CODE REVIEW

**Comment by mathias-baumann-frequenz** [comment]
I can't really tell if this PR is good or not. It looks good, but I just don't know about the removed modules. Someone with more xp should check this

**Comment by ela-kotulska-frequenz** [comment]
We should make sure on the actors meeting that no one is using module to load historic data.
Recently David was using it. To be postponed to the next actors meeting.

**Review by ela-kotulska-frequenz — APPROVED** [review]

**Comment by ela-kotulska-frequenz** [comment]
Rebased and merged in https://github.com/frequenz-floss/frequenz-sdk-python/pull/232

**Comment by ela-kotulska-frequenz** [comment]
Rebased and merged in https://github.com/frequenz-floss/frequenz-sdk-python/pull/232

**Pull request closed without merging**
