### PR TITLE
Update the SDK codebase to work with the latest channel version

### PR DESCRIPTION
**Pull request by shsms**

### CODE REVIEW

**Comment by leandro-lucarella-frequenz** [comment]
Oh, nice! When you said make a PR I thought you meant to just pin the dependency with a hash without the API changes :D

The bad news is I will get a lot of conflicts when rebasing my work on #73 on top of this :scream:

**Comment by shsms** [comment]
> The bad news is I will get a lot of conflicts when rebasing my work on https://github.com/frequenz-floss/frequenz-sdk-python/issues/73 on top of this :scream:

This one is easy to redo,  if you want to take #73 first.

**Comment by leandro-lucarella-frequenz** [comment]
I will give the rebase a chance and let you know if it messes up my stuff too much.

**Review by leandro-lucarella-frequenz — APPROVED** [review]
Feel free to merge, I rebased my changes on top of this without much trouble!

**Pull request merged**
