### PR TITLE
Cherry pick missing commits from shsms/log-api-request-times

### PR DESCRIPTION
**Pull request by ela-kotulska-frequenz**

### CODE REVIEW

**Comment by llucax** [comment]
Something's wrong, tests are timing out

**Comment by shsms** [comment]
Could you please remove the second commit:  "Stop PV inverter when it is not known to be working"

We don't need it anymore because we figured out the missing data issues.  And I'm working on an alternative approach now.

Then you could change the PR description to the title of the first commit.  And maybe add a note in the description that this is temporary and will be changed once we have the two upcoming features fallback components and fallback values merged.

**Comment by ela-kotulska-frequenz** [comment]
Abandon, because of misunderstanding. fallback formulas are almost ready now

**Comment by ela-kotulska-frequenz** [comment]
Abandon, because of misunderstanding. fallback formulas are almost ready now

**Comment by llucax** [comment]
Sorry for the noise Ela! :disappointed:

**Pull request closed without merging**
