### PR TITLE
Add new labels to the CI and issue templates

### PR DESCRIPTION
**Pull request by leandro-lucarella-frequenz**
- Sort labels alphabetically
- Add new labels

### CODE REVIEW

**Comment by ela-kotulska-frequenz** [comment]
LGTM however it is possible to create an issue without assigning Labels.
Can you force people to set labels? One shouldn't be allowed to create issue without (at least) one label.

**Review by ela-kotulska-frequenz — DISMISSED** [review]

**Comment by leandro-lucarella-frequenz** [comment]
> LGTM however it is possible to create an issue without assigning Labels.
> Can you force people to set labels? One shouldn't be allowed to create issue without (at least) one label.

Not sure what you mean exactly. I can disable the "Open a blank issue." option, but I think is good to have an escape mechanism, I hate when for reporting something that doesn't fit a template I'm force to fill a thousand of senseless fields in a template :)

And I think that link is *hidden* enough, so I don't think it will be *abused*.

**Comment by leandro-lucarella-frequenz** [comment]
Rebased. I enabled auto-merge, so if you want this not to be merged after an approval, don't approve yet!

**Review by ela-kotulska-frequenz — COMMENTED** [review]
LGTM

**Comment by leandro-lucarella-frequenz** [comment]
OK, force merging because of the lack of formal approval again :)

**Pull request merged**
