### PR TITLE
Indent multi-line return value descriptions in docstrings

### PR DESCRIPTION
**Pull request by shsms**

### CODE REVIEW

**Review by leandro-lucarella-frequenz — COMMENTED** [review]
I guess you did this with an automatic tool and this is why it is also *affecting* `Args:`, `Raises:` and some body function, right? It might be a good idea to mention this in the commit too, but it is just a nitpick so I'm fine with leaving it as it is too.

But I would delay merging this until the documentation generation is merged (it should be soon-ish), so we can actually check the results are now correct, or did you somehow tested it?

**Comment by sahas-subramanian-frequenz** [comment]
> I guess you did this with an automatic tool and this is why it is also affecting Args:, Raises: and some body function, right? It might be a good idea to mention this in the commit too, but it is just a nitpick so I'm fine with leaving it as it is too.

I've updated the commit message.

> did you somehow tested it

no,  do you have the documentation generation code in your fork?  maybe that can be rebased on this to test?

**Comment by leandro-lucarella-frequenz** [comment]
Sorry, not yet because I starting cleaning up and building the final config for the channels repo instead, so we can use the cross-reference here, so I will create a PR first to that repo.

**Comment by leandro-lucarella-frequenz** [comment]
@sahas-subramanian-frequenz I created a (draft) PR for the channels repo: https://github.com/frequenz-floss/frequenz-channels-python/pull/25, it should be fairly easy to just apply the same patch to this repo and try it out if you are very eager to do so, otherwise we can just wait a bit longer to merge this :)

**Review by leandro-lucarella-frequenz — DISMISSED** [review]
This was already tested in the channels repo, so let's merge it! :shipit:

**Comment by shsms** [comment]
Rebased on to latest 0.x.x

**Review by sahas-subramanian-frequenz — APPROVED** [review]

**Pull request merged**
