### PR TITLE
Some component status cleanup

### PR DESCRIPTION
**Pull request by shsms**
- Refactor component status tracking into its own package.
- Use `timedelta`s instead of `float`s for duration in component status trackers.
- Convert `ComponentStatusTracker`s into `BackgroundService`s

### CODE REVIEW

**Comment by shsms** [comment]
Only internal improvements, no release notes necessary.

**Review by llucax — APPROVED** [review]
Awesome! I'm just curious about `Use a cached zero duration value, instead of repeatedly allocating`, did this showed up in some benchmark?

**Comment by shsms** [comment]
> did this showed up in some benchmark?

no, but they do allocate in the hot path, which is many times slower than referencing a cached value.

**Comment by llucax** [comment]
Yeah, creating objects is really slow. Not sure if there will be any caching going on when creating the same (immutable) object over and over though.

**Pull request merged**
